# Build settings

markdown: kramdown
permalink: pretty
collections:
 - casestudy
 - upskilling
include: ["_pages"]
layouts_dir:  _templates/_layouts
includes_dir: _templates/_includes
data_dir: _data
sass:
    sass_dir: _templates/_sass







