# Build settings

markdown: kramdown
permalink: pretty
collections:

  casestudy:
     output: true
     permalink: /casestudy/:path/
  upskilling_cs:
     output: true
     permalink: /upskilling_cs/:path/
  jobboard:   
  

include: ["_pages"]







